# Generated by Django 5.0.4 on 2025-10-03 07:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sbdapp", "0002_galleryimage_testimonial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image",
        ),
    ]
