# Generated by Django 5.0.4 on 2025-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sbdapp", "0003_remove_testimonial_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="category",
            field=models.CharField(
                choices=[("interior", "Interior"), ("sliding", "Sliding")],
                default="interior",
                max_length=20,
            ),
        ),
    ]
