# Generated by Django 5.0.4 on 2025-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sbdapp", "0004_galleryimage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryimage",
            name="category",
            field=models.CharField(
                choices=[
                    ("interior", "Interior"),
                    ("sliding", "Sliding"),
                    ("construction", "Construction"),
                ],
                default="interior",
                max_length=20,
            ),
        ),
    ]
